



var PropertyListing= angular.module('PropertyListingApp', [] ); 



PropertyListing.controller('Mainctrl', function($scope,$location) {

   

                  console.log("url"+$location.absUrl())

$scope.data=[
	{"tag":"Sale",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"Kes",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"sale",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"},
	{"tag":"for Rent",
	"title":"Apartment",
	"name":"Watamu Bay",
	"currency":"$",
	"price":"11000",
	"location":"3398 Lodgeville Road",
	"curency":"Ksh",
	"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et dui vestibulum",
	"status":"Rent",
	"size":"860",
    "beds":"3",
    "baths":"4",
    "assetimg":"/images/assets/apartment.png",
	"propertyimg":"/images/properties/prop2.jpg",
	"propertyid":"1"}
    ];



});